// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SonnetDB.AspNetCoreWebMvcWithIdentity.Data;

#nullable disable

namespace SonnetDB.AspNetCoreWebMvcWithIdentity.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261007135609_CreateIdentitySchema")]
    partial class CreateIdentitySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("STRING");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("STRING");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("STRING");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("STRING");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", null, t =>
                        {
                            t.HasCheckConstraint("CK_AspNetRoles_Name_MaxLength", "\"Name\" IS NULL OR char_length(\"Name\") <= 256");

                            t.HasCheckConstraint("CK_AspNetRoles_NormalizedName_MaxLength", "\"NormalizedName\" IS NULL OR char_length(\"NormalizedName\") <= 256");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    b.Property<string>("ClaimType")
                        .HasColumnType("STRING");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("STRING");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("STRING");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("STRING");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("STRING");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("STRING");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("BOOL");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("BOOL");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("DATETIME");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("STRING");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("STRING");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("STRING");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("STRING");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("BOOL");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("STRING");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("BOOL");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("STRING");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_AspNetUsers_Email_MaxLength", "\"Email\" IS NULL OR char_length(\"Email\") <= 256");

                            t.HasCheckConstraint("CK_AspNetUsers_NormalizedEmail_MaxLength", "\"NormalizedEmail\" IS NULL OR char_length(\"NormalizedEmail\") <= 256");

                            t.HasCheckConstraint("CK_AspNetUsers_NormalizedUserName_MaxLength", "\"NormalizedUserName\" IS NULL OR char_length(\"NormalizedUserName\") <= 256");

                            t.HasCheckConstraint("CK_AspNetUsers_UserName_MaxLength", "\"UserName\" IS NULL OR char_length(\"UserName\") <= 256");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    b.Property<string>("ClaimType")
                        .HasColumnType("STRING");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("STRING");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("STRING");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("STRING");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("STRING");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("STRING");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("STRING");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", null, t =>
                        {
                            t.HasCheckConstraint("CK_AspNetUserLogins_LoginProvider_MaxLength", "\"LoginProvider\" IS NULL OR char_length(\"LoginProvider\") <= 128");

                            t.HasCheckConstraint("CK_AspNetUserLogins_ProviderKey_MaxLength", "\"ProviderKey\" IS NULL OR char_length(\"ProviderKey\") <= 128");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("STRING");

                    b.Property<string>("RoleId")
                        .HasColumnType("STRING");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("STRING");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("STRING");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("STRING");

                    b.Property<string>("Value")
                        .HasColumnType("STRING");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_AspNetUserTokens_LoginProvider_MaxLength", "\"LoginProvider\" IS NULL OR char_length(\"LoginProvider\") <= 128");

                            t.HasCheckConstraint("CK_AspNetUserTokens_Name_MaxLength", "\"Name\" IS NULL OR char_length(\"Name\") <= 128");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
