services:
  sonnetdb:
    build:
      context: .
      dockerfile: src/SonnetDB/Dockerfile
      secrets:
        - sixlabors-license

secrets:
  sixlabors-license:
    file: ${SixLaborsLicenseFile:-./sixlabors.lic}
