<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../extensions/SonnetDB.Media/SonnetDB.Media.csproj" />
    <None Include="transcript.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
